#include "CPU.h"
#include "Instructions.h"

// Complete 6502 opcode table (256 entries)
// Format: {Mnemonic, AddressingMode, Cycles, FunctionPointer, AddCycleOnPageCross}
const Instruction INSTRUCTION_TABLE[256] = {
    // 0x00-0x0F
    /* 0x00 */ {"BRK", &CPU::BRK, &CPU::IMP, 7},
    /* 0x01 */ {"ORA", &CPU::ORA, &CPU::IZX, 6},
    /* 0x02 */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0x03 */ {"XXX", &CPU::XXX, &CPU::IMP, 8},
    /* 0x04 */ {"NOP", &CPU::NOP, &CPU::ZP0, 3},
    /* 0x05 */ {"ORA", &CPU::ORA, &CPU::ZP0, 3},
    /* 0x06 */ {"ASL", &CPU::ASL, &CPU::ZP0, 5},
    /* 0x07 */ {"XXX", &CPU::XXX, &CPU::IMP, 5},
    /* 0x08 */ {"PHP", &CPU::PHP, &CPU::IMP, 3},
    /* 0x09 */ {"ORA", &CPU::ORA, &CPU::IMM, 2},
    /* 0x0A */ {"ASL", &CPU::ASL, &CPU::ACC, 2},
    /* 0x0B */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0x0C */ {"NOP", &CPU::NOP, &CPU::ABS, 4},
    /* 0x0D */ {"ORA", &CPU::ORA, &CPU::ABS, 4},
    /* 0x0E */ {"ASL", &CPU::ASL, &CPU::ABS, 6},
    /* 0x0F */ {"XXX", &CPU::XXX, &CPU::IMP, 6},

    // 0x10-0x1F
    /* 0x10 */ {"BPL", &CPU::BPL, &CPU::REL, 2},
    /* 0x11 */ {"ORA", &CPU::ORA, &CPU::IZY, 5},
    /* 0x12 */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0x13 */ {"XXX", &CPU::XXX, &CPU::IMP, 8},
    /* 0x14 */ {"NOP", &CPU::NOP, &CPU::ZPX, 4},
    /* 0x15 */ {"ORA", &CPU::ORA, &CPU::ZPX, 4},
    /* 0x16 */ {"ASL", &CPU::ASL, &CPU::ZPX, 6},
    /* 0x17 */ {"XXX", &CPU::XXX, &CPU::IMP, 6},
    /* 0x18 */ {"CLC", &CPU::CLC, &CPU::IMP, 2},
    /* 0x19 */ {"ORA", &CPU::ORA, &CPU::ABY, 4},
    /* 0x1A */ {"NOP", &CPU::NOP, &CPU::IMP, 2},
    /* 0x1B */ {"XXX", &CPU::XXX, &CPU::IMP, 7},
    /* 0x1C */ {"NOP", &CPU::NOP, &CPU::ABX, 4},
    /* 0x1D */ {"ORA", &CPU::ORA, &CPU::ABX, 4},
    /* 0x1E */ {"ASL", &CPU::ASL, &CPU::ABX, 7},
    /* 0x1F */ {"XXX", &CPU::XXX, &CPU::IMP, 7},

    // 0x20-0x2F
    /* 0x20 */ {"JSR", &CPU::JSR, &CPU::ABS, 6},
    /* 0x21 */ {"AND", &CPU::AND, &CPU::IZX, 6},
    /* 0x22 */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0x23 */ {"XXX", &CPU::XXX, &CPU::IMP, 8},
    /* 0x24 */ {"BIT", &CPU::BIT, &CPU::ZP0, 3},
    /* 0x25 */ {"AND", &CPU::AND, &CPU::ZP0, 3},
    /* 0x26 */ {"ROL", &CPU::ROL, &CPU::ZP0, 5},
    /* 0x27 */ {"XXX", &CPU::XXX, &CPU::IMP, 5},
    /* 0x28 */ {"PLP", &CPU::PLP, &CPU::IMP, 4},
    /* 0x29 */ {"AND", &CPU::AND, &CPU::IMM, 2},
    /* 0x2A */ {"ROL", &CPU::ROL, &CPU::ACC, 2},
    /* 0x2B */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0x2C */ {"BIT", &CPU::BIT, &CPU::ABS, 4},
    /* 0x2D */ {"AND", &CPU::AND, &CPU::ABS, 4},
    /* 0x2E */ {"ROL", &CPU::ROL, &CPU::ABS, 6},
    /* 0x2F */ {"XXX", &CPU::XXX, &CPU::IMP, 6},

    // 0x30-0x3F
    /* 0x30 */ {"BMI", &CPU::BMI, &CPU::REL, 2},
    /* 0x31 */ {"AND", &CPU::AND, &CPU::IZY, 5},
    /* 0x32 */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0x33 */ {"XXX", &CPU::XXX, &CPU::IMP, 8},
    /* 0x34 */ {"NOP", &CPU::NOP, &CPU::ZPX, 4},
    /* 0x35 */ {"AND", &CPU::AND, &CPU::ZPX, 4},
    /* 0x36 */ {"ROL", &CPU::ROL, &CPU::ZPX, 6},
    /* 0x37 */ {"XXX", &CPU::XXX, &CPU::IMP, 6},
    /* 0x38 */ {"SEC", &CPU::SEC, &CPU::IMP, 2},
    /* 0x39 */ {"AND", &CPU::AND, &CPU::ABY, 4},
    /* 0x3A */ {"NOP", &CPU::NOP, &CPU::IMP, 2},
    /* 0x3B */ {"XXX", &CPU::XXX, &CPU::IMP, 7},
    /* 0x3C */ {"NOP", &CPU::NOP, &CPU::ABX, 4},
    /* 0x3D */ {"AND", &CPU::AND, &CPU::ABX, 4},
    /* 0x3E */ {"ROL", &CPU::ROL, &CPU::ABX, 7},
    /* 0x3F */ {"XXX", &CPU::XXX, &CPU::IMP, 7},

    // 0x40-0x4F
    /* 0x40 */ {"RTI", &CPU::RTI, &CPU::IMP, 6},
    /* 0x41 */ {"EOR", &CPU::EOR, &CPU::IZX, 6},
    /* 0x42 */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0x43 */ {"XXX", &CPU::XXX, &CPU::IMP, 8},
    /* 0x44 */ {"NOP", &CPU::NOP, &CPU::ZP0, 3},
    /* 0x45 */ {"EOR", &CPU::EOR, &CPU::ZP0, 3},
    /* 0x46 */ {"LSR", &CPU::LSR, &CPU::ZP0, 5},
    /* 0x47 */ {"XXX", &CPU::XXX, &CPU::IMP, 5},
    /* 0x48 */ {"PHA", &CPU::PHA, &CPU::IMP, 3},
    /* 0x49 */ {"EOR", &CPU::EOR, &CPU::IMM, 2},
    /* 0x4A */ {"LSR", &CPU::LSR, &CPU::ACC, 2},
    /* 0x4B */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0x4C */ {"JMP", &CPU::JMP, &CPU::ABS, 3},
    /* 0x4D */ {"EOR", &CPU::EOR, &CPU::ABS, 4},
    /* 0x4E */ {"LSR", &CPU::LSR, &CPU::ABS, 6},
    /* 0x4F */ {"XXX", &CPU::XXX, &CPU::IMP, 6},

    // 0x50-0x5F
    /* 0x50 */ {"BVC", &CPU::BVC, &CPU::REL, 2},
    /* 0x51 */ {"EOR", &CPU::EOR, &CPU::IZY, 5},
    /* 0x52 */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0x53 */ {"XXX", &CPU::XXX, &CPU::IMP, 8},
    /* 0x54 */ {"NOP", &CPU::NOP, &CPU::ZPX, 4},
    /* 0x55 */ {"EOR", &CPU::EOR, &CPU::ZPX, 4},
    /* 0x56 */ {"LSR", &CPU::LSR, &CPU::ZPX, 6},
    /* 0x57 */ {"XXX", &CPU::XXX, &CPU::IMP, 6},
    /* 0x58 */ {"CLI", &CPU::CLI, &CPU::IMP, 2},
    /* 0x59 */ {"EOR", &CPU::EOR, &CPU::ABY, 4},
    /* 0x5A */ {"NOP", &CPU::NOP, &CPU::IMP, 2},
    /* 0x5B */ {"XXX", &CPU::XXX, &CPU::IMP, 7},
    /* 0x5C */ {"NOP", &CPU::NOP, &CPU::ABX, 4},
    /* 0x5D */ {"EOR", &CPU::EOR, &CPU::ABX, 4},
    /* 0x5E */ {"LSR", &CPU::LSR, &CPU::ABX, 7},
    /* 0x5F */ {"XXX", &CPU::XXX, &CPU::IMP, 7},

    // 0x60-0x6F
    /* 0x60 */ {"RTS", &CPU::RTS, &CPU::IMP, 6},
    /* 0x61 */ {"ADC", &CPU::ADC, &CPU::IZX, 6},
    /* 0x62 */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0x63 */ {"XXX", &CPU::XXX, &CPU::IMP, 8},
    /* 0x64 */ {"NOP", &CPU::NOP, &CPU::ZP0, 3},
    /* 0x65 */ {"ADC", &CPU::ADC, &CPU::ZP0, 3},
    /* 0x66 */ {"ROR", &CPU::ROR, &CPU::ZP0, 5},
    /* 0x67 */ {"XXX", &CPU::XXX, &CPU::IMP, 5},
    /* 0x68 */ {"PLA", &CPU::PLA, &CPU::IMP, 4},
    /* 0x69 */ {"ADC", &CPU::ADC, &CPU::IMM, 2},
    /* 0x6A */ {"ROR", &CPU::ROR, &CPU::ACC, 2},
    /* 0x6B */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0x6C */ {"JMP", &CPU::JMP, &CPU::IND, 5},
    /* 0x6D */ {"ADC", &CPU::ADC, &CPU::ABS, 4},
    /* 0x6E */ {"ROR", &CPU::ROR, &CPU::ABS, 6},
    /* 0x6F */ {"XXX", &CPU::XXX, &CPU::IMP, 6},

    // 0x70-0x7F
    /* 0x70 */ {"BVS", &CPU::BVS, &CPU::REL, 2},
    /* 0x71 */ {"ADC", &CPU::ADC, &CPU::IZY, 5},
    /* 0x72 */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0x73 */ {"XXX", &CPU::XXX, &CPU::IMP, 8},
    /* 0x74 */ {"NOP", &CPU::NOP, &CPU::ZPX, 4},
    /* 0x75 */ {"ADC", &CPU::ADC, &CPU::ZPX, 4},
    /* 0x76 */ {"ROR", &CPU::ROR, &CPU::ZPX, 6},
    /* 0x77 */ {"XXX", &CPU::XXX, &CPU::IMP, 6},
    /* 0x78 */ {"SEI", &CPU::SEI, &CPU::IMP, 2},
    /* 0x79 */ {"ADC", &CPU::ADC, &CPU::ABY, 4},
    /* 0x7A */ {"NOP", &CPU::NOP, &CPU::IMP, 2},
    /* 0x7B */ {"XXX", &CPU::XXX, &CPU::IMP, 7},
    /* 0x7C */ {"NOP", &CPU::NOP, &CPU::ABX, 4},
    /* 0x7D */ {"ADC", &CPU::ADC, &CPU::ABX, 4},
    /* 0x7E */ {"ROR", &CPU::ROR, &CPU::ABX, 7},
    /* 0x7F */ {"XXX", &CPU::XXX, &CPU::IMP, 7},

    // 0x80-0x8F
    /* 0x80 */ {"NOP", &CPU::NOP, &CPU::IMM, 2},
    /* 0x81 */ {"STA", &CPU::STA, &CPU::IZX, 6},
    /* 0x82 */ {"NOP", &CPU::NOP, &CPU::IMM, 2},
    /* 0x83 */ {"XXX", &CPU::XXX, &CPU::IMP, 6},
    /* 0x84 */ {"STY", &CPU::STY, &CPU::ZP0, 3},
    /* 0x85 */ {"STA", &CPU::STA, &CPU::ZP0, 3},
    /* 0x86 */ {"STX", &CPU::STX, &CPU::ZP0, 3},
    /* 0x87 */ {"XXX", &CPU::XXX, &CPU::IMP, 3},
    /* 0x88 */ {"DEY", &CPU::DEY, &CPU::IMP, 2},
    /* 0x89 */ {"NOP", &CPU::NOP, &CPU::IMM, 2},
    /* 0x8A */ {"TXA", &CPU::TXA, &CPU::IMP, 2},
    /* 0x8B */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0x8C */ {"STY", &CPU::STY, &CPU::ABS, 4},
    /* 0x8D */ {"STA", &CPU::STA, &CPU::ABS, 4},
    /* 0x8E */ {"STX", &CPU::STX, &CPU::ABS, 4},
    /* 0x8F */ {"XXX", &CPU::XXX, &CPU::IMP, 4},

    // 0x90-0x9F
    /* 0x90 */ {"BCC", &CPU::BCC, &CPU::REL, 2},
    /* 0x91 */ {"STA", &CPU::STA, &CPU::IZY, 6},
    /* 0x92 */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0x93 */ {"XXX", &CPU::XXX, &CPU::IMP, 6},
    /* 0x94 */ {"STY", &CPU::STY, &CPU::ZPX, 4},
    /* 0x95 */ {"STA", &CPU::STA, &CPU::ZPX, 4},
    /* 0x96 */ {"STX", &CPU::STX, &CPU::ZPY, 4},
    /* 0x97 */ {"XXX", &CPU::XXX, &CPU::IMP, 4},
    /* 0x98 */ {"TYA", &CPU::TYA, &CPU::IMP, 2},
    /* 0x99 */ {"STA", &CPU::STA, &CPU::ABY, 5},
    /* 0x9A */ {"TXS", &CPU::TXS, &CPU::IMP, 2},
    /* 0x9B */ {"XXX", &CPU::XXX, &CPU::IMP, 5},
    /* 0x9C */ {"XXX", &CPU::XXX, &CPU::IMP, 5},
    /* 0x9D */ {"STA", &CPU::STA, &CPU::ABX, 5},
    /* 0x9E */ {"XXX", &CPU::XXX, &CPU::IMP, 5},
    /* 0x9F */ {"XXX", &CPU::XXX, &CPU::IMP, 5},

    // 0xA0-0xAF
    /* 0xA0 */ {"LDY", &CPU::LDY, &CPU::IMM, 2},
    /* 0xA1 */ {"LDA", &CPU::LDA, &CPU::IZX, 6},
    /* 0xA2 */ {"LDX", &CPU::LDX, &CPU::IMM, 2},
    /* 0xA3 */ {"XXX", &CPU::XXX, &CPU::IMP, 6},
    /* 0xA4 */ {"LDY", &CPU::LDY, &CPU::ZP0, 3},
    /* 0xA5 */ {"LDA", &CPU::LDA, &CPU::ZP0, 3},
    /* 0xA6 */ {"LDX", &CPU::LDX, &CPU::ZP0, 3},
    /* 0xA7 */ {"XXX", &CPU::XXX, &CPU::IMP, 3},
    /* 0xA8 */ {"TAY", &CPU::TAY, &CPU::IMP, 2},
    /* 0xA9 */ {"LDA", &CPU::LDA, &CPU::IMM, 2},
    /* 0xAA */ {"TAX", &CPU::TAX, &CPU::IMP, 2},
    /* 0xAB */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0xAC */ {"LDY", &CPU::LDY, &CPU::ABS, 4},
    /* 0xAD */ {"LDA", &CPU::LDA, &CPU::ABS, 4},
    /* 0xAE */ {"LDX", &CPU::LDX, &CPU::ABS, 4},
    /* 0xAF */ {"XXX", &CPU::XXX, &CPU::IMP, 4},

    // 0xB0-0xBF
    /* 0xB0 */ {"BCS", &CPU::BCS, &CPU::REL, 2},
    /* 0xB1 */ {"LDA", &CPU::LDA, &CPU::IZY, 5},
    /* 0xB2 */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0xB3 */ {"XXX", &CPU::XXX, &CPU::IMP, 5},
    /* 0xB4 */ {"LDY", &CPU::LDY, &CPU::ZPX, 4},
    /* 0xB5 */ {"LDA", &CPU::LDA, &CPU::ZPX, 4},
    /* 0xB6 */ {"LDX", &CPU::LDX, &CPU::ZPY, 4},
    /* 0xB7 */ {"XXX", &CPU::XXX, &CPU::IMP, 4},
    /* 0xB8 */ {"CLV", &CPU::CLV, &CPU::IMP, 2},
    /* 0xB9 */ {"LDA", &CPU::LDA, &CPU::ABY, 4},
    /* 0xBA */ {"TSX", &CPU::TSX, &CPU::IMP, 2},
    /* 0xBB */ {"XXX", &CPU::XXX, &CPU::IMP, 4},
    /* 0xBC */ {"LDY", &CPU::LDY, &CPU::ABX, 4},
    /* 0xBD */ {"LDA", &CPU::LDA, &CPU::ABX, 4},
    /* 0xBE */ {"LDX", &CPU::LDX, &CPU::ABY, 4},
    /* 0xBF */ {"XXX", &CPU::XXX, &CPU::IMP, 4},

    // 0xC0-0xCF
    /* 0xC0 */ {"CPY", &CPU::CPY, &CPU::IMM, 2},
    /* 0xC1 */ {"CMP", &CPU::CMP, &CPU::IZX, 6},
    /* 0xC2 */ {"NOP", &CPU::NOP, &CPU::IMM, 2},
    /* 0xC3 */ {"XXX", &CPU::XXX, &CPU::IMP, 8},
    /* 0xC4 */ {"CPY", &CPU::CPY, &CPU::ZP0, 3},
    /* 0xC5 */ {"CMP", &CPU::CMP, &CPU::ZP0, 3},
    /* 0xC6 */ {"DEC", &CPU::DEC, &CPU::ZP0, 5},
    /* 0xC7 */ {"XXX", &CPU::XXX, &CPU::IMP, 5},
    /* 0xC8 */ {"INY", &CPU::INY, &CPU::IMP, 2},
    /* 0xC9 */ {"CMP", &CPU::CMP, &CPU::IMM, 2},
    /* 0xCA */ {"DEX", &CPU::DEX, &CPU::IMP, 2},
    /* 0xCB */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0xCC */ {"CPY", &CPU::CPY, &CPU::ABS, 4},
    /* 0xCD */ {"CMP", &CPU::CMP, &CPU::ABS, 4},
    /* 0xCE */ {"DEC", &CPU::DEC, &CPU::ABS, 6},
    /* 0xCF */ {"XXX", &CPU::XXX, &CPU::IMP, 6},

    // 0xD0-0xDF
    /* 0xD0 */ {"BNE", &CPU::BNE, &CPU::REL, 2},
    /* 0xD1 */ {"CMP", &CPU::CMP, &CPU::IZY, 5},
    /* 0xD2 */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0xD3 */ {"XXX", &CPU::XXX, &CPU::IMP, 8},
    /* 0xD4 */ {"NOP", &CPU::NOP, &CPU::ZPX, 4},
    /* 0xD5 */ {"CMP", &CPU::CMP, &CPU::ZPX, 4},
    /* 0xD6 */ {"DEC", &CPU::DEC, &CPU::ZPX, 6},
    /* 0xD7 */ {"XXX", &CPU::XXX, &CPU::IMP, 6},
    /* 0xD8 */ {"CLD", &CPU::CLD, &CPU::IMP, 2},
    /* 0xD9 */ {"CMP", &CPU::CMP, &CPU::ABY, 4},
    /* 0xDA */ {"NOP", &CPU::NOP, &CPU::IMP, 2},
    /* 0xDB */ {"XXX", &CPU::XXX, &CPU::IMP, 7},
    /* 0xDC */ {"NOP", &CPU::NOP, &CPU::ABX, 4},
    /* 0xDD */ {"CMP", &CPU::CMP, &CPU::ABX, 4},
    /* 0xDE */ {"DEC", &CPU::DEC, &CPU::ABX, 7},
    /* 0xDF */ {"XXX", &CPU::XXX, &CPU::IMP, 7},

    // 0xE0-0xEF
    /* 0xE0 */ {"CPX", &CPU::CPX, &CPU::IMM, 2},
    /* 0xE1 */ {"SBC", &CPU::SBC, &CPU::IZX, 6},
    /* 0xE2 */ {"NOP", &CPU::NOP, &CPU::IMM, 2},
    /* 0xE3 */ {"XXX", &CPU::XXX, &CPU::IMP, 8},
    /* 0xE4 */ {"CPX", &CPU::CPX, &CPU::ZP0, 3},
    /* 0xE5 */ {"SBC", &CPU::SBC, &CPU::ZP0, 3},
    /* 0xE6 */ {"INC", &CPU::INC, &CPU::ZP0, 5},
    /* 0xE7 */ {"XXX", &CPU::XXX, &CPU::IMP, 5},
    /* 0xE8 */ {"INX", &CPU::INX, &CPU::IMP, 2},
    /* 0xE9 */ {"SBC", &CPU::SBC, &CPU::IMM, 2},
    /* 0xEA */ {"NOP", &CPU::NOP, &CPU::IMP, 2},
    /* 0xEB */ {"SBC", &CPU::SBC, &CPU::IMM, 2}, // 0xEB unofficial SBC
    /* 0xEC */ {"CPX", &CPU::CPX, &CPU::ABS, 4},
    /* 0xED */ {"SBC", &CPU::SBC, &CPU::ABS, 4},
    /* 0xEE */ {"INC", &CPU::INC, &CPU::ABS, 6},
    /* 0xEF */ {"XXX", &CPU::XXX, &CPU::IMP, 6},

    // 0xF0-0xFF
    /* 0xF0 */ {"BEQ", &CPU::BEQ, &CPU::REL, 2},
    /* 0xF1 */ {"SBC", &CPU::SBC, &CPU::IZY, 5},
    /* 0xF2 */ {"XXX", &CPU::XXX, &CPU::IMP, 2},
    /* 0xF3 */ {"XXX", &CPU::XXX, &CPU::IMP, 8},
    /* 0xF4 */ {"NOP", &CPU::NOP, &CPU::ZPX, 4},
    /* 0xF5 */ {"SBC", &CPU::SBC, &CPU::ZPX, 4},
    /* 0xF6 */ {"INC", &CPU::INC, &CPU::ZPX, 6},
    /* 0xF7 */ {"XXX", &CPU::XXX, &CPU::IMP, 6},
    /* 0xF8 */ {"SED", &CPU::SED, &CPU::IMP, 2},
    /* 0xF9 */ {"SBC", &CPU::SBC, &CPU::ABY, 4},
    /* 0xFA */ {"NOP", &CPU::NOP, &CPU::IMP, 2},
    /* 0xFB */ {"XXX", &CPU::XXX, &CPU::IMP, 7},
    /* 0xFC */ {"NOP", &CPU::NOP, &CPU::ABX, 4},
    /* 0xFD */ {"SBC", &CPU::SBC, &CPU::ABX, 4},
    /* 0xFE */ {"INC", &CPU::INC, &CPU::ABX, 7},
    /* 0xFF */ {"XXX", &CPU::XXX, &CPU::IMP, 7}
};