#ifndef MIRROR_MODE_H
#define MIRROR_MODE_H

enum MirrorMode
{
    MIRROR_MODE_HORIZONTAL,
    MIRROR_MODE_VERTICAL,
    MIRROR_MODE_FOUR_SCREEN,
    MIRROR_MODE_ONE_SCREEN_LOWER,
    MIRROR_MODE_ONE_SCREEN_UPPER
};

#endif